
import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

// Professional Color Palettes for User Types
export const USER_PALETTES = {
  student: {
    light: {
      primary: '#1976D2',        // Professional Blue
      primaryVariant: '#0D47A1',  
      secondary: '#1565C0',
      accent: '#42A5F5',
      surface: '#F8FAFF',
      background: '#FFFFFF',
      card: '#FFFFFF',
      gradient: ['#1976D2', '#1565C0'],
      text: {
        primary: '#1A1A1A',
        secondary: '#424242',
        disabled: '#9E9E9E'
      }
    },
    dark: {
      primary: '#64B5F6',
      primaryVariant: '#42A5F5',
      secondary: '#90CAF9',
      accent: '#BBDEFB',
      surface: '#1A1A2E',
      background: '#0F0F23',
      card: '#16213E',
      gradient: ['#64B5F6', '#42A5F5'],
      text: {
        primary: '#FFFFFF',
        secondary: '#E0E0E0',
        disabled: '#757575'
      }
    }
  },
  instructor: {
    light: {
      primary: '#2E7D32',        // Professional Green
      primaryVariant: '#1B5E20',
      secondary: '#388E3C',
      accent: '#66BB6A',
      surface: '#F1F8E9',
      background: '#FFFFFF',
      card: '#FFFFFF',
      gradient: ['#2E7D32', '#388E3C'],
      text: {
        primary: '#1A1A1A',
        secondary: '#424242',
        disabled: '#9E9E9E'
      }
    },
    dark: {
      primary: '#81C784',
      primaryVariant: '#66BB6A',
      secondary: '#A5D6A7',
      accent: '#C8E6C9',
      surface: '#1A2E1A',
      background: '#0F230F',
      card: '#163E16',
      gradient: ['#81C784', '#66BB6A'],
      text: {
        primary: '#FFFFFF',
        secondary: '#E0E0E0',
        disabled: '#757575'
      }
    }
  },
  admin: {
    light: {
      primary: '#6A1B9A',        // Professional Purple
      primaryVariant: '#4A148C',
      secondary: '#8E24AA',
      accent: '#AB47BC',
      surface: '#F3E5F5',
      background: '#FFFFFF',
      card: '#FFFFFF',
      gradient: ['#6A1B9A', '#8E24AA'],
      text: {
        primary: '#1A1A1A',
        secondary: '#424242',
        disabled: '#9E9E9E'
      }
    },
    dark: {
      primary: '#CE93D8',
      primaryVariant: '#BA68C8',
      secondary: '#E1BEE7',
      accent: '#F8BBD9',
      surface: '#2E1A2E',
      background: '#230F23',
      card: '#3E163E',
      gradient: ['#CE93D8', '#BA68C8'],
      text: {
        primary: '#FFFFFF',
        secondary: '#E0E0E0',
        disabled: '#757575'
      }
    }
  }
};

// Default themes (fallback)
const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#1976D2',
    secondary: '#388E3C',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    error: '#D32F2F',
    success: '#2E7D32',
    warning: '#F57C00',
    text: '#212121',
    disabled: '#BDBDBD',
  },
  roundness: 8,
};

const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#64B5F6',
    secondary: '#81C784',
    background: '#121212',
    surface: '#1E1E1E',
    error: '#CF6679',
    success: '#81C784',
    warning: '#FFB74D',
    text: '#FFFFFF',
    disabled: '#6D6D6D',
  },
  roundness: 8,
};

// Function to get theme for specific user type
export const getThemeForUserType = (userType, isDarkMode = false) => {
  const palette = USER_PALETTES[userType] || USER_PALETTES.student;
  const colorScheme = isDarkMode ? palette.dark : palette.light;
  
  const baseTheme = isDarkMode ? darkTheme : lightTheme;
  
  return {
    ...baseTheme,
    colors: {
      ...baseTheme.colors,
      primary: colorScheme.primary,
      primaryVariant: colorScheme.primaryVariant,
      secondary: colorScheme.secondary,
      background: colorScheme.background,
      surface: colorScheme.surface,
      card: colorScheme.card,
      text: colorScheme.text.primary,
      // Custom colors for our app
      accent: colorScheme.accent,
      gradient: colorScheme.gradient,
      textSecondary: colorScheme.text.secondary,
      textDisabled: colorScheme.text.disabled,
    },
    userType,
    palette: colorScheme
  };
};

// Export themes for backward compatibility

// Languages configuration
export const languages = {
  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇧🇷',
    strings: {
      // Login Screen
      appName: 'Academia App',
      welcome: 'Bem-vindo de volta!',
      email: 'Email',
      password: 'Senha',
      login: 'Entrar',
      forgotPassword: 'Esqueci minha senha',
      register: 'Criar conta',
      language: 'Idioma',
      darkMode: 'Modo escuro',
      error: 'Erro',
      fillAllFields: 'Por favor, preencha todos os campos',
      loginError: 'Erro no Login',
      checkCredentials: 'Verifique suas credenciais',
      userNotFound: 'Usuário não encontrado',
      wrongPassword: 'Senha incorreta',
      invalidCredentials: 'Email ou senha inválidos. Verifique seus dados e tente novamente.',
      invalidEmail: 'Email inválido',
      loggingIn: 'Fazendo login...',
      
      // Social Login
      orLoginWith: 'Ou entre com:',
      
      // Registration Screen
      createAccount: 'Criar Conta',
      fillDataToRegister: 'Preencha os dados para se cadastrar',
      personalData: 'Dados Pessoais',
      fullName: 'Nome Completo *',
      phoneWhatsApp: 'Telefone/WhatsApp',
      userType: 'Tipo de Usuário',
      passwordSection: 'Senha',
      confirmPassword: 'Confirmar Senha *',
      creatingAccount: 'Criando conta...',
      alreadyHaveAccount: 'Já tem uma conta?',
      signIn: 'Entrar',
      
      // User Types
      student: 'Aluno',
      instructor: 'Professor',
      administrator: 'Administrador',
      studentDescription: 'Acesso às aulas e evolução',
      instructorDescription: 'Gerenciar turmas e alunos',
      adminDescription: 'Controle total do sistema',
      
      // Validation Messages
      nameRequired: 'Nome é obrigatório',
      emailRequired: 'Email é obrigatório',
      passwordMinLength: 'Senha deve ter pelo menos 6 caracteres',
      passwordsMismatch: 'Senhas não coincidem',
      
      // Success and Error Messages
      accountCreatedSuccess: 'Conta criada com sucesso! 🎉',
      registrationError: 'Erro ao criar conta',
      emailAlreadyInUse: 'Este email já está em uso',
      weakPassword: 'Senha muito fraca',
      googleLoginError: 'Erro ao fazer login com Google',
      facebookLoginError: 'Erro ao fazer login com Facebook',
      microsoftLoginError: 'Erro ao fazer login com Microsoft',
      appleLoginError: 'Erro ao fazer login com Apple',
      
      // Common
      required: 'obrigatório',
      success: 'Sucesso',
      loading: 'Carregando...',
      save: 'Salvar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      delete: 'Excluir',
      edit: 'Editar',
      back: 'Voltar',
      next: 'Próximo',
      finish: 'Finalizar',
      yes: 'Sim',
      no: 'Não',
      ok: 'OK',
      
      // Fallback messages
      recoverPassword: 'Recuperar Senha',
      contactSupport: 'Entre em contato com o suporte para recuperar sua senha.',
      registrationDevelopment: 'Funcionalidade de cadastro em desenvolvimento',
      
      // Navigation and Menu
      dashboard: 'Dashboard',
      payments: 'Pagamentos',
      evolution: 'Evolução',
      calendar: 'Calendário',
      reports: 'Relatórios',
      classes: 'Turmas',
      students: 'Alunos',
      management: 'Gestão',
      invitations: 'Convites',
      settings: 'Configurações',
      profile: 'Perfil',
      notifications: 'Notificações',
      academy: 'Academia',
      
      // Form Labels and Placeholders
      selectOption: 'Selecione uma opção',
      typeNumber: 'Digite o número',
      academyCodeOrLink: 'Código da academia ou link completo',
      searchStudents: 'Buscar alunos...',
      searchClasses: 'Buscar turmas...',
      academyCode: 'Código da Academia',
      postalCode: 'CEP/Código Postal',
      number: 'Número',
      address: 'Endereço',
      emergencyContact: 'Contato de Emergência',
      medicalInformation: 'Informações Médicas',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condições médicas...',
      birthDate: 'Data de Nascimento',
      birthDatePlaceholder: '01/01/1990',
      goals: 'Objetivos',
      goalsPlaceholder: 'Perda de peso, ganho de massa, condicionamento...',
      medicalConditions: 'Condições Médicas (opcional)',
      medicalConditionsPlaceholder: 'Informe alergias, lesões, medicamentos, etc.',
      emergencyPhone: 'Telefone de Emergência',
      addressOptional: 'Endereço (opcional)',
      
      // Physical Evaluation
      physicalEvaluations: 'Avaliações físicas',
      physicalEvaluation: 'Avaliação Física',
      myInjuries: 'Minhas Lesões',
      currentGraduation: 'Graduação Atual',
      startDate: 'Data de Início',
      evaluationNotes: 'Observações sobre a avaliação',
      evaluationNotesPlaceholder: 'Ex: Início de nova dieta, mudança no treino, etc.',
      
      // Injury Management
      injuryDescription: 'Descrição da Lesão',
      injuryDescriptionPlaceholder: 'Descreva como a lesão ocorreu, sintomas, etc.',
      treatment: 'Tratamento',
      treatmentPlaceholder: 'Ex: Fisioterapia, medicamentos, repouso...',
      medicalNotes: 'Observações Médicas',
      medicalNotesPlaceholder: 'Instruções do médico, diagnóstico...',
      recoveryTime: 'Tempo de Recuperação',
      recoveryTimePlaceholder: 'Ex: 2 semanas, 1 mês...',
      restrictions: 'Restrições',
      restrictionsPlaceholder: 'Ex: Não fazer força com o braço, evitar corrida...',
      
      // Class Management
      description: 'Descrição',
      descriptionOptional: 'Descrição (opcional)',
      maxStudents: 'Máximo de Alunos',
      schedule: 'Horário',
      scheduleExample: 'Ex: Segunda 19:00',
      scheduleDetailed: 'Horário (ex: Segunda-feira 08:00-09:00)',
      monthlyPrice: 'Preço Mensal (R$)',
      maxCapacity: 'Capacidade Máxima',
      className: 'Nome da Turma',
      
      // Student Management
      phoneNotInformed: 'Telefone não informado',
      disassociationReason: 'Motivo da desassociação *',
      disassociationReasonPlaceholder: 'Informe o motivo da desassociação (ex: inadimplência, solicitação do aluno, etc.)',
      minAge: 'Idade mín.',
      maxAge: 'Idade máx.',
      until: 'Até (AAAA-MM-DD)',
      
      // Payment and Dates
      dueDatePlaceholder: 'DD/MM/AAAA',
      
      // User Information
      user: 'Usuário',
      personalInformation: 'Informações pessoais e configurações',
      updatePassword: 'Atualizar sua senha de acesso',
      changePassword: 'Alterar Senha',
      bodyMeasurements: 'Registre suas medidas corporais',
      physicalEvolution: 'Acompanhe sua evolução física',
      
      // Evolution and Goals
      maintainFrequency: 'Manter frequência nas aulas',
      improveTechniques: 'Aperfeiçoar técnicas',
      nextGraduation: 'Próxima graduação',
      
      // Statistics
      thisMonth: 'Este mês',
      plusThisMonth: '+15 este mês',
      averageFrequency: 'Frequência Média',
      plusVsLastMonth: '+3% vs mês anterior',
      
      // Admin Actions
      quickActions: 'Ações Rápidas',
      modalitiesConfig: 'Configurar modalidades',
      preferencesManagement: 'Preferências e gestão',
      addGraduation: 'Adicionar Graduação',
      
      // Error Messages
      cannotLoadPayments: 'Não foi possível carregar os pagamentos',
      whatsappNotFound: 'Número do WhatsApp da academia não encontrado',
      cannotOpenWhatsapp: 'Não foi possível abrir o WhatsApp',
      logoutNotAvailable: 'Função de logout não está disponível. Recarregue o app.',
      cannotLogout: 'Não foi possível fazer logout. Tente novamente.',
      cannotLoadClasses: 'Não foi possível carregar as aulas',
      cannotUpdateProfile: 'Não foi possível atualizar o perfil',
      cannotDeleteClass: 'Não foi possível excluir a turma. Verifique suas permissões.',
      cannotLoadStudents: 'Não foi possível carregar os alunos',
      cannotDeleteStudent: 'Não foi possível excluir o aluno',
      invalidCode: 'Digite um código válido',
      cannotProcessCode: 'Não foi possível processar o código',
      invalidQRCode: 'QR Code inválido',
      invalidOrExpiredInvite: 'Convite inválido ou expirado',
      invalidLink: 'Link inválido',
      pleaseValidEmail: 'Por favor, digite um email válido',
      userDataNotFound: 'Dados de usuário ou aula não encontrados',
      cannotCopyLink: 'Não foi possível copiar o link',
      checkInTimeError: 'Check-in só pode ser feito 15 minutos antes ou depois do horário da aula',
      
      // Success Messages
      classDeletedSuccess: 'Turma excluída com sucesso',
      studentDeletedSuccess: 'Aluno excluído com sucesso',
      
      // Development Messages
      inDevelopment: 'Em Desenvolvimento',
      exportFeatureComingSoon: 'Funcionalidade de exportação será implementada em breve',
      featureComingSoon: 'Funcionalidade será implementada em breve',
      limitedInformation: 'Algumas informações podem estar limitadas. Tente novamente mais tarde.',
      adminOnlyFeature: 'Funcionalidade disponível apenas para administradores',
      
      // Alert Titles
      checkIn: 'Check-in',
      warning: 'Aviso',
      info: 'Info',
      mandatorySelection: 'Seleção Obrigatória',
      pleaseSelectUserType: 'Por favor, selecione o tipo de usuário.',
      cannotSaveUserType: 'Não foi possível salvar o tipo de usuário. Tente novamente.',
      
      // Notification Service
      congratsNewGraduation: 'Parabéns! Nova Graduação',
      newAnnouncement: 'Novo Anúncio',
      
      // Logout Confirmation
      confirmExit: 'Confirmar Saída',
      sureToLogout: 'Tem certeza que deseja sair da sua conta?',
      exit: 'Sair',
      
      // Payment Status
      paid: 'Pago',
      pending: 'Pendente',
      overdue: 'Atrasado',
      notInformed: 'Não informado',
      pixPayment: 'Pagamento PIX',
      pixFeatureComingSoon: 'Funcionalidade de pagamento PIX será implementada em breve',
      
      // Navigation Titles
      newClass: 'Nova Turma',
      classStudents: 'Alunos da Turma',
      editClass: 'Editar Turma',
      classDetails: 'Detalhes da Turma',
      checkIns: 'Check-ins',
      newStudent: 'Novo Aluno',
      editStudent: 'Editar Aluno',
      studentDetails: 'Detalhes do Aluno',
      studentPayments: 'Pagamentos do Aluno',
      reports: 'Relatórios',
      newLesson: 'Nova Aula',
      myProfile: 'Meu Perfil',
      changePassword: 'Alterar Senha',
      physicalEvaluation: 'Avaliação Física',
      evaluationHistory: 'Histórico de Avaliações',
      manageInjury: 'Gerenciar Lesão',
      myInjuries: 'Minhas Lesões',
      privacyPolicy: 'Política de Privacidade',
      notificationSettings: 'Configurações de Notificação',
      privacySettings: 'Configurações de Privacidade',
      
      // Navigation Subtitles
      personalInfoAndSettings: 'Informações pessoais e configurações',
      updateYourPassword: 'Atualizar sua senha de acesso',
      recordBodyMeasurements: 'Registre suas medidas corporais',
      trackPhysicalEvolution: 'Acompanhe sua evolução física',
      recordAndTrackInjuries: 'Registre e acompanhe lesões',
      injuryHistoryAndRecovery: 'Histórico de lesões e recuperação',
      dataProtectionAndLGPD: 'Proteção de dados e LGPD',
      manageYourNotifications: 'Gerencie suas notificações',
      lgpdAndDataProtection: 'LGPD e proteção de dados',
      
      // Tab Navigation
      dashboard: 'Painel',
      payments: 'Pagamentos',
      evolution: 'Evolução',
      calendar: 'Calendário',
      students: 'Alunos',
      classes: 'Turmas',
      modalities: 'Modalidades',
      checkIn: 'Check-in',
      instructorReports: 'Relatórios',
      lessons: 'Aulas',
      studentDashboard: 'Painel do Aluno',
      invites: 'Convites',
      
      // Profile Screen
      loadingStudentData: 'Erro ao carregar dados do aluno',
      loadingPaymentData: 'Erro ao carregar pagamento atual',
      checkingPaymentDue: 'Erro ao verificar vencimento',
      monthlyPayment: 'Mensalidade',
      profileUpdatedSuccess: 'Perfil atualizado com sucesso',
      cannotUpdateProfile: 'Não foi possível atualizar o perfil',
      confirmLogout: 'Tem certeza que deseja sair da sua conta?',
      logout: 'Sair',
      user: 'Usuário',
      paymentNearDue: 'Pagamento Próximo do Vencimento',
      paymentDueToday: 'hoje',
      paymentDueTomorrow: 'amanhã',
      paymentDueInDays: 'dias',
      paymentDueText: 'Seu pagamento de {planName} vence em {days}',
      dateLabel: 'Data',
      valueLabel: 'Valor',
      changeDate: 'Alterar Data',
      payNow: 'Pagar Agora',
      personalInformation: 'Informações Pessoais',
      cancel: 'Cancelar',
      edit: 'Editar',
      fullName: 'Nome Completo',
      phoneWhatsApp: 'Telefone/WhatsApp',
      address: 'Endereço',
      emergencyContact: 'Contato de Emergência',
      medicalInformation: 'Informações Médicas',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condições médicas...',
      saveChanges: 'Salvar Alterações',
      name: 'Nome',
      phone: 'Telefone',
      notInformed: 'Não informado',
      academyInformation: 'Informações da Academia',
      currentGraduation: 'Graduação Atual',
      beginner: 'Iniciante',
      currentPlan: 'Plano Atual',
      notDefined: 'Não definido',
      startDate: 'Data de Início',
      contracts: 'Contratos',
      nextDueDate: 'Próximo vencimento',
      checkIns: 'Check-ins',
      checkInsThisWeek: 'Check-ins na semana',
      physicalEvaluations: 'Avaliações físicas',
      evaluationsRegistered: 'avaliação(ões) registrada(s)',
      noEvaluationsRegistered: 'Nenhuma avaliação registrada',
      myInjuries: 'Minhas Lesões',
      injuriesRegistered: 'lesão(ões) registrada(s)',
      noInjuriesRegistered: 'Nenhuma lesão registrada',
      noTrainingThisWeek: 'Nenhum treino esta semana',
      
      // Forgot Password Screen
      emailRequired: 'Email é obrigatório',
      invalidEmail: 'Email inválido',
      pleaseValidEmail: 'Por favor, digite um email válido',
      emailSentSuccess: 'Email enviado! ⚠️ IMPORTANTE: Verifique sua caixa de SPAM/LIXO ELETRÔNICO, pois emails de recuperação frequentemente são filtrados.',
      resetPasswordError: 'Erro ao enviar email de recuperação',
      emailNotFound: 'Email não encontrado. Verifique se está correto ou crie uma conta.',
      invalidEmailFormat: 'Email inválido. Verifique o formato.',
      tooManyRequests: 'Muitas tentativas. Aguarde alguns minutos e tente novamente.',
      networkError: 'Erro de conexão. Verifique sua internet e tente novamente.',
      configurationNotFound: 'Configuração de email não encontrada. Entre em contato com o suporte.',
      close: 'Fechar',
      recoverPassword: 'Recuperar Senha',
      enterEmailForInstructions: 'Digite seu email para receber instruções',
      sendEmail: 'Enviar Email',
      emailSent: 'Email Enviado!',
      checkInboxInstructions: 'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
      spamFolderWarning: '⚠️ IMPORTANTE: Se não encontrar o email, verifique sua pasta de SPAM/LIXO ELETRÔNICO, pois emails de recuperação são frequentemente filtrados.',
      backToLogin: 'Voltar ao Login',
      
      // Academia Selection Screen
      enterAcademyCode: 'Digite o código da academia',
      academyFoundSuccess: 'Academia encontrada com sucesso!',
      academyNotFound: 'Academia não encontrada. Verifique o código e tente novamente',
      errorSearchingAcademy: 'Erro ao buscar academia. Tente novamente',
      associatedSuccessfully: 'Você foi associado à academia com sucesso!',
      errorAssociating: 'Erro ao associar à academia. Tente novamente',
      invalidQRCode: 'QR Code inválido',
      errorProcessingQR: 'Erro ao processar QR Code',
      invalidOrExpiredInvite: 'Convite inválido ou expirado',
      errorProcessingInvite: 'Erro ao processar convite',
      enterInviteLink: 'Digite o link do convite',
      invalidLink: 'Link inválido',
      errorProcessingInviteLink: 'Erro ao processar link do convite',
      permissionDenied: 'Permissão Negada',
      onlyAdminsCanCreate: 'Apenas usuários com perfil de administrador podem criar uma nova academia.',
      currentProfile: 'Seu perfil atual',
      notDefined: 'não definido',
      academyNameRequired: 'Nome da academia é obrigatório',
      emailRequired: 'Email é obrigatório',
      cityRequired: 'Cidade é obrigatória',
      streetRequired: 'Rua/Avenida é obrigatória',
      phoneRequired: 'Telefone é obrigatório',
      invalidEmail: 'Email inválido',
      academyCreatedSuccess: 'Academia Criada com Sucesso! 🎉',
      academyCreatedMessage: 'Sua academia foi criada!\n\n📋 CÓDIGO DA ACADEMIA: {code}\n\n⚠️ IMPORTANTE: Anote este código! Os usuários precisarão dele para se associar à sua academia.\n\nVocê será redirecionado para o dashboard em alguns segundos.',
      copyCode: 'Copiar Código',
      ok: 'OK',
      cannotCreateAcademy: 'Não foi possível criar a academia. Tente novamente',
      addressNotInformed: 'Endereço não informado',
      logoutError: 'Erro ao fazer logout',
      errorLoggingOut: 'Erro ao sair. Tente novamente.',
      createAcademy: 'Criar Academia',
      selectAcademy: 'Selecionar Academia',
      adminMustCreate: 'Como administrador, você precisa criar uma nova academia',
      mustAssociate: 'Para continuar, você precisa se associar a uma academia',
      academyCode: 'Código da Academia',
      academyCodePlaceholder: 'Ex: ABC123',

      // Privacy Settings Screen
      privacySettings: 'Configurações de Privacidade',
      lgpdStatus: 'Status LGPD',
      consents: 'Consentimentos',
      lgpdInfo: 'A Lei Geral de Proteção de Dados (LGPD) garante seus direitos sobre seus dados pessoais. Configure abaixo como seus dados podem ser utilizados.',
      consentGivenOn: 'Consentimento inicial dado em:',
      dataProcessingConsent: 'Processamento de Dados Pessoais',
      dataProcessingDescription: 'Permitir o uso de dados para funcionamento básico do app',
      marketingConsent: 'Comunicações de Marketing',
      marketingDescription: 'Receber ofertas, promoções e novidades',
      analyticsConsent: 'Análise e Melhorias',
      analyticsDescription: 'Usar dados para melhorar o app e serviços',
      thirdPartyConsent: 'Compartilhamento com Terceiros',
      thirdPartyDescription: 'Permitir compartilhamento com parceiros (opcional)',
      profileVisibility: 'Visibilidade do Perfil',
      profileVisibilityDescription: 'Atualmente:',
      public: 'Público',
      academy: 'Apenas Academia',
      private: 'Privado',
      shareTrainingData: 'Compartilhar Dados de Treino',
      shareTrainingDescription: 'Permitir que instrutores vejam seu progresso',
      shareProgressData: 'Compartilhar Dados de Progresso',
      shareProgressDescription: 'Permitir comparações e estatísticas gerais',
      contactMethods: 'Formas de Contato',
      whatsappContact: 'Contato via WhatsApp',
      whatsappDescription: 'Permitir contato da academia via WhatsApp',
      emailContact: 'Contato via Email',
      emailDescription: 'Permitir contato da academia via email',
      phoneContact: 'Contato via Telefone',
      phoneDescription: 'Permitir ligações da academia',
      yourRights: 'Seus Direitos',
      exportData: 'Exportar Meus Dados',
      exportDescription: 'Baixar uma cópia de todos os seus dados',
      privacyPolicy: 'Política de Privacidade',
      privacyPolicyDescription: 'Ler nossa política de privacidade completa',
      deleteData: 'Excluir Meus Dados',
      deleteDescription: 'Solicitar exclusão permanente de todos os dados',
      importantInfo: 'Informações Importantes',
      infoChangeConsents: '• Você pode alterar seus consentimentos a qualquer momento',
      infoRequiredConsents: '• Alguns consentimentos são necessários para o funcionamento básico do app',
      infoProcessingTime: '• Solicitações de exportação e exclusão são processadas em até 30 dias',
      infoContact: '• Para dúvidas sobre privacidade, entre em contato conosco',
      saveSettings: 'Salvar Configurações',
      settingsSavedSuccess: 'Configurações de privacidade salvas com sucesso',
      settingsSaveError: 'Não foi possível salvar as configurações',
      exportDataTitle: 'Exportar Dados',
      exportDataMessage: 'Você receberá um arquivo com todos os seus dados pessoais em até 30 dias, conforme previsto na LGPD.',
      requestSent: 'Solicitação Enviada',
      exportRequestMessage: 'Sua solicitação foi registrada. Você receberá os dados por email em até 30 dias.',
      deleteDataTitle: 'Excluir Dados',
      deleteDataWarning: 'ATENÇÃO: Esta ação irá excluir permanentemente todos os seus dados pessoais. Esta ação não pode ser desfeita.',
      finalConfirmation: 'Confirmação Final',
      deleteConfirmMessage: 'Tem certeza absoluta que deseja excluir todos os seus dados? Você perderá acesso à sua conta.',
      deleteAll: 'Sim, excluir tudo',
      requestRegistered: 'Solicitação Registrada',
      deleteRequestMessage: 'Sua solicitação de exclusão foi registrada. Os dados serão removidos em até 30 dias.',
      privacyPolicyError: 'Não foi possível abrir a política de privacidade',
      profileVisibilityTitle: 'Visibilidade do Perfil',
      profileVisibilityQuestion: 'Quem pode ver suas informações básicas?',
      onlyAcademy: 'Apenas Academia',

      // Admin Classes Screen
      searchClasses: 'Buscar turmas...',
      allClasses: 'Todas',
      activeClasses: 'Ativas',
      inactiveClasses: 'Inativas',
      fullClasses: 'Lotadas',
      emptyClasses: 'Vazias',
      noInstructor: 'Sem Professor',
      notAssigned: 'Não atribuído',
      errorLoadingClasses: 'Não foi possível carregar as turmas',
      confirmDeletion: 'Confirmar Exclusão',
      confirmDeleteClass: 'Tem certeza que deseja excluir a turma {className}?',
      classDeletedSuccess: 'Turma excluída com sucesso',
      errorDeletingClass: 'Não foi possível excluir a turma',
      edit: 'Editar',
      delete: 'Excluir',
      professor: 'Professor',
      scheduleNotDefined: 'Horário não definido',
      students: 'alunos',
      active: 'Ativa',
      inactive: 'Inativa',
      full: 'Lotada',
      withoutInstructor: 'Sem Professor',
      viewDetails: 'Ver Detalhes',
      studentsTab: 'Alunos',
      noClassesFound: 'Nenhuma turma encontrada',
      noMatchingClasses: 'Nenhuma turma corresponde à sua busca',
      noClassesRegistered: 'Nenhuma turma cadastrada ainda',
      classStatistics: 'Estatísticas das Turmas',
      total: 'Total',
      totalStudents: 'Total Alunos',
      modalities: 'Modalidades',
      newClass: 'Nova Turma',

      // Admin Modalities Screen
      fightModalities: 'Modalidades de Luta',
      paymentPlans: 'Planos de Pagamento',
      announcementBoard: 'Mural de Avisos',
      add: 'Adicionar',
      publish: 'Publicar',
      noDescription: 'Sem descrição',
      noModalitiesRegistered: 'Nenhuma modalidade cadastrada',
      noPlansRegistered: 'Nenhum plano cadastrado',
      noAnnouncementsPublished: 'Nenhum aviso publicado',
      summary: 'Resumo',
      plans: 'Planos',
      activeAnnouncements: 'Avisos Ativos',
      errorLoadingData: 'Não foi possível carregar os dados',
      modalityNameRequired: 'Nome da modalidade é obrigatório',
      modalityCreatedSuccess: 'Modalidade criada com sucesso',
      errorCreatingModality: 'Não foi possível criar a modalidade',
      confirmDeleteModality: 'Tem certeza que deseja excluir a modalidade {modalityName}?\n\nEsta ação não pode ser desfeita.',
      modalityDeletedSuccess: 'Modalidade excluída com sucesso!',
      errorDeletingModality: 'Não foi possível excluir a modalidade.\n\nMotivo: {error}',
      planNameAndValueRequired: 'Nome e valor do plano são obrigatórios',
      planCreatedSuccess: 'Plano criado com sucesso',
      errorCreatingPlan: 'Não foi possível criar o plano',
      confirmDeletePlan: 'Tem certeza que deseja excluir o plano {planName}?\n\nEsta ação não pode ser desfeita.',
      planDeletedSuccess: 'Plano excluído com sucesso!',
      errorDeletingPlan: 'Não foi possível excluir o plano.\n\nMotivo: {error}',
      announcementTitleAndContentRequired: 'Título e conteúdo do aviso são obrigatórios',
      announcementPublishedSuccess: 'Aviso publicado com sucesso',
      errorPublishingAnnouncement: 'Não foi possível publicar o aviso',
      confirmDeleteAnnouncement: 'Tem certeza que deseja excluir o aviso "{announcementTitle}"?\n\nEsta ação não pode ser desfeita.',
      announcementDeletedSuccess: 'Aviso excluído com sucesso!',
      errorDeletingAnnouncement: 'Não foi possível excluir o aviso.\n\nMotivo: {error}',
      noExpirationDate: 'Sem data de expiração',
      expiresOn: 'Expira em:',
      newModality: 'Nova Modalidade',
      modalityName: 'Nome da Modalidade',
      optionalDescription: 'Descrição (opcional)',
      create: 'Criar',
      newPlan: 'Novo Plano',
      planName: 'Nome do Plano',
      valueInReais: 'Valor (R$)',
      durationMonths: 'Duração (meses)',
      months: 'mês(es)',
      newAnnouncement: 'Novo Aviso',
      announcementTitle: 'Título do Aviso',
      content: 'Conteúdo',
      optionalExpirationDate: 'Data de Expiração (opcional)',
      targetAudience: 'Público-alvo:',
      all: 'Todos',
      students: 'Alunos',
      instructors: 'Instrutores',

      // Instructor Dashboard Screen
      hello: 'Olá',
      martialArtsInstructor: 'Instrutor de Artes Marciais',
      online: 'Online',
      myClasses: 'Minhas Turmas',
      totalStudents: 'Total Alunos',
      classesToday: 'Aulas Hoje',
      checkIns: 'Check-ins',
      todaySchedule: 'Agenda de Hoje',
      classesScheduled: 'aula(s) programada(s)',
      noClassesToday: 'Nenhuma aula hoje',
      planNextClasses: 'Aproveite para planejar suas próximas aulas',
      quickActions: 'Ações Rápidas',
      directAccessFunctionalities: 'Acesso direto às principais funcionalidades',
      newClass: 'Nova Aula',
      createNewClass: 'Criar nova turma',
      create: 'Criar',
      checkIn: 'Check-in',
      digitalAttendance: 'Presença digital',
      open: 'Abrir',
      reports: 'Relatórios',
      dataAnalysis: 'Análise de dados',
      view: 'Ver',
      announcements: 'Avisos',
      importantCommunications: 'Comunicados importantes',
      update: 'Atualizar',
      loadingAnnouncements: 'Carregando avisos...',
      important: 'Importante',
      noAnnouncementsNow: 'Nenhum aviso no momento',
      notifyNewCommunications: 'Você será notificado quando houver novos comunicados',
      recentGraduations: 'Graduações Recentes',
      noRecentGraduations: 'Nenhuma graduação recente',
      viewAllGraduations: 'Ver Todas as Graduações',
      upcomingClasses: 'Próximas Aulas',
      noUpcomingClasses: 'Nenhuma aula próxima',
      viewAllClasses: 'Ver Todas as Turmas',
      scheduleNotDefined: 'Horário não definido',
      students: 'alunos',
      manageClass: 'Gerenciar Aula',
      errorLoadingAnnouncements: 'Erro ao carregar anúncios:',
      errorLoadingData: 'Erro ao carregar',
      couldNotLoadAnnouncements: 'Não foi possível carregar os avisos. Tente novamente mais tarde.',
      now: 'Agora',
      unknownDate: 'Data desconhecida',
      today: 'Hoje',
      yesterday: 'Ontem',
      daysAgo: 'Há {days} dias',
      errorFormattingDate: 'Erro ao formatar data:',
      loadingInstructorDashboard: '📊 Carregando dashboard do instrutor:',
      classesLoaded: '✅ {count} turmas carregadas',
      errorSearchingClasses: '⚠️ Erro ao buscar turmas via service:',
      fallbackClasses: '✅ Fallback: {count} turmas encontradas',
      fallbackClassesError: '❌ Falha no fallback para turmas:',
      studentsLoaded: '✅ {count} alunos carregados',
      errorSearchingStudents: '⚠️ Erro ao buscar alunos via service:',
      instructorDashboardLoaded: '✅ Dashboard do instrutor carregado com sucesso',
      generalErrorLoadingDashboard: 'Erro geral ao carregar dashboard do professor:',

      // InstructorStudents Screen
      searchStudents: 'Buscar alunos...',
      allStudents: 'Todos',
      activeStudents: 'Ativos',
      inactiveStudents: 'Inativos',
      paymentPendingStudents: 'Pagamento Pendente',
      allGenders: 'Todos os sexos',
      male: 'Masculino',
      female: 'Feminino',
      other: 'Outro',
      minAge: 'Idade mínima',
      maxAge: 'Idade máxima',
      enrollmentStart: 'Matrícula início',
      enrollmentEnd: 'Matrícula fim',
      clearFilters: 'Limpar Filtros',
      applyFilters: 'Aplicar Filtros',
      viewProfile: 'Ver Perfil',
      graduation: 'Graduação',
      paymentUpToDate: 'Em dia',
      paymentPending: 'Pendente',
      paymentOverdue: 'Atrasado',
      paymentNA: 'N/A',
      noStudentsFound: 'Nenhum aluno encontrado',
      noStudentsMessage: 'Você ainda não tem alunos cadastrados.',
      modality: 'Modalidade',
      allModalities: 'Todas modalidades',
      loadingStudentsInstructor: '👥 Carregando dados do instrutor:',
      searchingStudentsCreatedBy: '🔍 Tentando buscar alunos criados por este instrutor...',
      studentsFoundCreatedBy: '✅ {count} alunos encontrados via createdBy',
      errorSearchingStudentsService: '⚠️ Erro ao buscar alunos via service:',
      fallbackStudentsFound: '✅ Fallback: {count} alunos encontrados',
      errorFallback: '❌ Erro no fallback:',
      classesFound: '✅ {count} turmas encontradas',
      errorSearchingClasses: '⚠️ Erro ao buscar turmas:',
      modalitiesLoaded: '✅ {count} modalidades carregadas',
      errorSearchingModalities: '⚠️ Erro ao buscar modalidades:',
      instructorDataLoaded: '✅ Dados do instrutor carregados com sucesso',
      generalErrorLoadingInstructorData: 'Erro geral ao carregar dados do instrutor:',
      limitedInfoWarning: 'Algumas informações podem estar limitadas. Tente novamente mais tarde.',

      // Language Detection
      language: 'pt',
    }
  },
  en: {
    code: 'en',
    name: 'English',
    flag: '🇺🇸',
    strings: {
      // Login Screen
      appName: 'Academia App',
      welcome: 'Welcome back!',
      email: 'Email',
      password: 'Password',
      login: 'Login',
      forgotPassword: 'Forgot password',
      register: 'Create account',
      language: 'Language',
      darkMode: 'Dark mode',
      error: 'Error',
      fillAllFields: 'Please fill all fields',
      loginError: 'Login Error',
      checkCredentials: 'Check your credentials',
      userNotFound: 'User not found',
      wrongPassword: 'Wrong password',
      invalidCredentials: 'Invalid email or password. Please check your credentials and try again.',
      invalidEmail: 'Invalid email',
      loggingIn: 'Logging in...',
      
      // Social Login
      orLoginWith: 'Or sign in with:',
      
      // Registration Screen
      createAccount: 'Create Account',
      fillDataToRegister: 'Fill in the data to register',
      personalData: 'Personal Data',
      fullName: 'Full Name *',
      phoneWhatsApp: 'Phone/WhatsApp',
      userType: 'User Type',
      passwordSection: 'Password',
      confirmPassword: 'Confirm Password *',
      creatingAccount: 'Creating account...',
      alreadyHaveAccount: 'Already have an account?',
      signIn: 'Sign In',
      
      // User Types
      student: 'Student',
      instructor: 'Instructor',
      administrator: 'Administrator',
      studentDescription: 'Access to classes and progress',
      instructorDescription: 'Manage classes and students',
      adminDescription: 'Full system control',
      
      // Validation Messages
      nameRequired: 'Name is required',
      emailRequired: 'Email is required',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordsMismatch: 'Passwords do not match',
      
      // Success and Error Messages
      accountCreatedSuccess: 'Account created successfully! 🎉',
      registrationError: 'Error creating account',
      emailAlreadyInUse: 'This email is already in use',
      weakPassword: 'Password too weak',
      googleLoginError: 'Error signing in with Google',
      facebookLoginError: 'Error signing in with Facebook',
      microsoftLoginError: 'Error signing in with Microsoft',
      appleLoginError: 'Error signing in with Apple',
      
      // Common
      required: 'required',
      success: 'Success',
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      back: 'Back',
      next: 'Next',
      finish: 'Finish',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      
      // Fallback messages
      recoverPassword: 'Recover Password',
      contactSupport: 'Please contact support to recover your password.',
      registrationDevelopment: 'Registration feature under development',
      
      // Navigation and Menu
      dashboard: 'Dashboard',
      payments: 'Payments',
      evolution: 'Evolution',
      calendar: 'Calendar',
      reports: 'Reports',
      classes: 'Classes',
      students: 'Students',
      management: 'Management',
      invitations: 'Invitations',
      settings: 'Settings',
      profile: 'Profile',
      notifications: 'Notifications',
      academy: 'Academy',
      
      // Form Labels and Placeholders
      selectOption: 'Select an option',
      typeNumber: 'Type the number',
      academyCodeOrLink: 'Academy code or complete link',
      searchStudents: 'Search students...',
      searchClasses: 'Search classes...',
      academyCode: 'Academy Code',
      postalCode: 'ZIP/Postal Code',
      number: 'Number',
      address: 'Address',
      emergencyContact: 'Emergency Contact',
      medicalInformation: 'Medical Information',
      allergiesMedicationsConditions: 'Allergies, medications, medical conditions...',
      birthDate: 'Birth Date',
      birthDatePlaceholder: '01/01/1990',
      goals: 'Goals',
      goalsPlaceholder: 'Weight loss, muscle gain, conditioning...',
      medicalConditions: 'Medical Conditions (optional)',
      medicalConditionsPlaceholder: 'Report allergies, injuries, medications, etc.',
      emergencyPhone: 'Emergency Phone',
      addressOptional: 'Address (optional)',
      
      // Physical Evaluation
      physicalEvaluations: 'Physical evaluations',
      physicalEvaluation: 'Physical Evaluation',
      myInjuries: 'My Injuries',
      currentGraduation: 'Current Graduation',
      startDate: 'Start Date',
      evaluationNotes: 'Evaluation notes',
      evaluationNotesPlaceholder: 'E.g.: New diet start, training change, etc.',
      
      // Injury Management
      injuryDescription: 'Injury Description',
      injuryDescriptionPlaceholder: 'Describe how the injury occurred, symptoms, etc.',
      treatment: 'Treatment',
      treatmentPlaceholder: 'E.g.: Physical therapy, medications, rest...',
      medicalNotes: 'Medical Notes',
      medicalNotesPlaceholder: 'Doctor instructions, diagnosis...',
      recoveryTime: 'Recovery Time',
      recoveryTimePlaceholder: 'E.g.: 2 weeks, 1 month...',
      restrictions: 'Restrictions',
      restrictionsPlaceholder: 'E.g.: No arm strength, avoid running...',
      
      // Class Management
      description: 'Description',
      descriptionOptional: 'Description (optional)',
      maxStudents: 'Maximum Students',
      schedule: 'Schedule',
      scheduleExample: 'E.g.: Monday 7:00 PM',
      scheduleDetailed: 'Schedule (e.g.: Monday 08:00-09:00)',
      monthlyPrice: 'Monthly Price ($)',
      maxCapacity: 'Maximum Capacity',
      className: 'Class Name',
      
      // Student Management
      phoneNotInformed: 'Phone not provided',
      disassociationReason: 'Reason for disassociation *',
      disassociationReasonPlaceholder: 'Provide reason for disassociation (e.g.: non-payment, student request, etc.)',
      minAge: 'Min age',
      maxAge: 'Max age',
      until: 'Until (YYYY-MM-DD)',
      
      // Payment and Dates
      dueDatePlaceholder: 'MM/DD/YYYY',
      
      // User Information
      user: 'User',
      personalInformation: 'Personal information and settings',
      updatePassword: 'Update your access password',
      changePassword: 'Change Password',
      bodyMeasurements: 'Record your body measurements',
      physicalEvolution: 'Track your physical evolution',
      
      // Evolution and Goals
      maintainFrequency: 'Maintain class attendance',
      improveTechniques: 'Improve techniques',
      nextGraduation: 'Next graduation',
      
      // Statistics
      thisMonth: 'This month',
      plusThisMonth: '+15 this month',
      averageFrequency: 'Average Frequency',
      plusVsLastMonth: '+3% vs last month',
      
      // Admin Actions
      quickActions: 'Quick Actions',
      modalitiesConfig: 'Configure modalities',
      preferencesManagement: 'Preferences and management',
      addGraduation: 'Add Graduation',
      
      // Error Messages
      cannotLoadPayments: 'Could not load payments',
      whatsappNotFound: 'Academy WhatsApp number not found',
      cannotOpenWhatsapp: 'Could not open WhatsApp',
      logoutNotAvailable: 'Logout function not available. Reload the app.',
      cannotLogout: 'Could not logout. Please try again.',
      cannotLoadClasses: 'Could not load classes',
      cannotUpdateProfile: 'Could not update profile',
      cannotDeleteClass: 'Could not delete class. Check your permissions.',
      cannotLoadStudents: 'Could not load students',
      cannotDeleteStudent: 'Could not delete student',
      invalidCode: 'Enter a valid code',
      cannotProcessCode: 'Could not process code',
      invalidQRCode: 'Invalid QR Code',
      invalidOrExpiredInvite: 'Invalid or expired invitation',
      invalidLink: 'Invalid link',
      pleaseValidEmail: 'Please enter a valid email',
      userDataNotFound: 'User or class data not found',
      cannotCopyLink: 'Could not copy link',
      checkInTimeError: 'Check-in can only be done 15 minutes before or after class time',
      
      // Success Messages
      classDeletedSuccess: 'Class deleted successfully',
      studentDeletedSuccess: 'Student deleted successfully',
      
      // Development Messages
      inDevelopment: 'Under Development',
      exportFeatureComingSoon: 'Export feature will be implemented soon',
      featureComingSoon: 'Feature will be implemented soon',
      limitedInformation: 'Some information may be limited. Please try again later.',
      adminOnlyFeature: 'Feature available only for administrators',
      
      // Alert Titles
      checkIn: 'Check-in',
      warning: 'Warning',
      info: 'Info',
      mandatorySelection: 'Mandatory Selection',
      pleaseSelectUserType: 'Please select the user type.',
      cannotSaveUserType: 'Could not save user type. Please try again.',
      
      // Notification Service
      congratsNewGraduation: 'Congratulations! New Graduation',
      newAnnouncement: 'New Announcement',
      
      // Logout Confirmation
      confirmExit: 'Confirm Exit',
      sureToLogout: 'Are you sure you want to logout?',
      exit: 'Exit',
      
      // Payment Status
      paid: 'Paid',
      pending: 'Pending',
      overdue: 'Overdue',
      notInformed: 'Not informed',
      pixPayment: 'PIX Payment',
      pixFeatureComingSoon: 'PIX payment feature will be implemented soon',
      
      // Navigation Titles
      newClass: 'New Class',
      classStudents: 'Class Students',
      editClass: 'Edit Class',
      classDetails: 'Class Details',
      checkIns: 'Check-ins',
      newStudent: 'New Student',
      editStudent: 'Edit Student',
      studentDetails: 'Student Details',
      studentPayments: 'Student Payments',
      reports: 'Reports',
      newLesson: 'New Lesson',
      myProfile: 'My Profile',
      changePassword: 'Change Password',
      physicalEvaluation: 'Physical Evaluation',
      evaluationHistory: 'Evaluation History',
      manageInjury: 'Manage Injury',
      myInjuries: 'My Injuries',
      privacyPolicy: 'Privacy Policy',
      notificationSettings: 'Notification Settings',
      privacySettings: 'Privacy Settings',
      
      // Navigation Subtitles
      personalInfoAndSettings: 'Personal information and settings',
      updateYourPassword: 'Update your access password',
      recordBodyMeasurements: 'Record your body measurements',
      trackPhysicalEvolution: 'Track your physical evolution',
      recordAndTrackInjuries: 'Record and track injuries',
      injuryHistoryAndRecovery: 'Injury history and recovery',
      dataProtectionAndLGPD: 'Data protection and LGPD',
      manageYourNotifications: 'Manage your notifications',
      lgpdAndDataProtection: 'LGPD and data protection',
      
      // Tab Navigation
      dashboard: 'Dashboard',
      payments: 'Payments',
      evolution: 'Evolution',
      calendar: 'Calendar',
      students: 'Students',
      classes: 'Classes',
      modalities: 'Modalities',
      checkIn: 'Check-in',
      instructorReports: 'Reports',
      lessons: 'Lessons',
      studentDashboard: 'Student Dashboard',
      invites: 'Invites',
      
      // Profile Screen
      loadingStudentData: 'Error loading student data',
      loadingPaymentData: 'Error loading current payment',
      checkingPaymentDue: 'Error checking payment due date',
      monthlyPayment: 'Monthly Payment',
      profileUpdatedSuccess: 'Profile updated successfully',
      cannotUpdateProfile: 'Could not update profile',
      confirmLogout: 'Are you sure you want to logout?',
      logout: 'Logout',
      user: 'User',
      paymentNearDue: 'Payment Near Due Date',
      paymentDueToday: 'today',
      paymentDueTomorrow: 'tomorrow',
      paymentDueInDays: 'days',
      paymentDueText: 'Your {planName} payment is due in {days}',
      dateLabel: 'Date',
      valueLabel: 'Amount',
      changeDate: 'Change Date',
      payNow: 'Pay Now',
      personalInformation: 'Personal Information',
      cancel: 'Cancel',
      edit: 'Edit',
      fullName: 'Full Name',
      phoneWhatsApp: 'Phone/WhatsApp',
      address: 'Address',
      emergencyContact: 'Emergency Contact',
      medicalInformation: 'Medical Information',
      allergiesMedicationsConditions: 'Allergies, medications, medical conditions...',
      saveChanges: 'Save Changes',
      name: 'Name',
      phone: 'Phone',
      notInformed: 'Not informed',
      academyInformation: 'Academy Information',
      currentGraduation: 'Current Graduation',
      beginner: 'Beginner',
      currentPlan: 'Current Plan',
      notDefined: 'Not defined',
      startDate: 'Start Date',
      contracts: 'Contracts',
      nextDueDate: 'Next due date',
      checkIns: 'Check-ins',
      checkInsThisWeek: 'Check-ins this week',
      physicalEvaluations: 'Physical evaluations',
      evaluationsRegistered: 'evaluation(s) registered',
      noEvaluationsRegistered: 'No evaluations registered',
      myInjuries: 'My Injuries',
      injuriesRegistered: 'injury(ies) registered',
      noInjuriesRegistered: 'No injuries registered',
      noTrainingThisWeek: 'No training this week',
      
      // Forgot Password Screen
      emailRequired: 'Email is required',
      invalidEmail: 'Invalid email',
      pleaseValidEmail: 'Please enter a valid email',
      emailSentSuccess: 'Email sent! ⚠️ IMPORTANT: Check your SPAM/JUNK folder, as recovery emails are often filtered.',
      resetPasswordError: 'Error sending recovery email',
      emailNotFound: 'Email not found. Check if it\'s correct or create an account.',
      invalidEmailFormat: 'Invalid email. Check the format.',
      tooManyRequests: 'Too many attempts. Wait a few minutes and try again.',
      networkError: 'Connection error. Check your internet and try again.',
      configurationNotFound: 'Email configuration not found. Contact support.',
      close: 'Close',
      recoverPassword: 'Recover Password',
      enterEmailForInstructions: 'Enter your email to receive instructions',
      sendEmail: 'Send Email',
      emailSent: 'Email Sent!',
      checkInboxInstructions: 'Check your inbox and follow the instructions to reset your password.',
      spamFolderWarning: '⚠️ IMPORTANT: If you don\'t find the email, check your SPAM/JUNK folder, as recovery emails are often filtered.',
      backToLogin: 'Back to Login',
      
      // Academia Selection Screen
      enterAcademyCode: 'Enter the academy code',
      academyFoundSuccess: 'Academy found successfully!',
      academyNotFound: 'Academy not found. Check the code and try again',
      errorSearchingAcademy: 'Error searching academy. Try again',
      associatedSuccessfully: 'You have been successfully associated with the academy!',
      errorAssociating: 'Error associating with academy. Try again',
      invalidQRCode: 'Invalid QR Code',
      errorProcessingQR: 'Error processing QR Code',
      invalidOrExpiredInvite: 'Invalid or expired invitation',
      errorProcessingInvite: 'Error processing invitation',
      enterInviteLink: 'Enter the invitation link',
      invalidLink: 'Invalid link',
      errorProcessingInviteLink: 'Error processing invitation link',
      permissionDenied: 'Permission Denied',
      onlyAdminsCanCreate: 'Only users with administrator profile can create a new academy.',
      currentProfile: 'Your current profile',
      notDefined: 'not defined',
      academyNameRequired: 'Academy name is required',
      emailRequired: 'Email is required',
      cityRequired: 'City is required',
      streetRequired: 'Street/Avenue is required',
      phoneRequired: 'Phone is required',
      invalidEmail: 'Invalid email',
      academyCreatedSuccess: 'Academy Created Successfully! 🎉',
      academyCreatedMessage: 'Your academy has been created!\n\n📋 ACADEMY CODE: {code}\n\n⚠️ IMPORTANT: Write down this code! Users will need it to associate with your academy.\n\nYou will be redirected to the dashboard in a few seconds.',
      copyCode: 'Copy Code',
      ok: 'OK',
      cannotCreateAcademy: 'Could not create academy. Try again',
      addressNotInformed: 'Address not informed',
      logoutError: 'Error logging out',
      errorLoggingOut: 'Error logging out. Try again.',
      createAcademy: 'Create Academy',
      selectAcademy: 'Select Academy',
      adminMustCreate: 'As an administrator, you need to create a new academy',
      mustAssociate: 'To continue, you need to associate with an academy',
      academyCode: 'Academy Code',
      academyCodePlaceholder: 'Ex: ABC123',

      // Privacy Settings Screen
      privacySettings: 'Privacy Settings',
      lgpdStatus: 'GDPR Status',
      consents: 'Consents',
      lgpdInfo: 'The General Data Protection Law (GDPR) guarantees your rights over your personal data. Configure below how your data can be used.',
      consentGivenOn: 'Initial consent given on:',
      dataProcessingConsent: 'Personal Data Processing',
      dataProcessingDescription: 'Allow data usage for basic app functionality',
      marketingConsent: 'Marketing Communications',
      marketingDescription: 'Receive offers, promotions and news',
      analyticsConsent: 'Analytics and Improvements',
      analyticsDescription: 'Use data to improve app and services',
      thirdPartyConsent: 'Third Party Sharing',
      thirdPartyDescription: 'Allow sharing with partners (optional)',
      profileVisibility: 'Profile Visibility',
      profileVisibilityDescription: 'Currently:',
      public: 'Public',
      academy: 'Academy Only',
      private: 'Private',
      shareTrainingData: 'Share Training Data',
      shareTrainingDescription: 'Allow instructors to see your progress',
      shareProgressData: 'Share Progress Data',
      shareProgressDescription: 'Allow comparisons and general statistics',
      contactMethods: 'Contact Methods',
      whatsappContact: 'WhatsApp Contact',
      whatsappDescription: 'Allow academy contact via WhatsApp',
      emailContact: 'Email Contact',
      emailDescription: 'Allow academy contact via email',
      phoneContact: 'Phone Contact',
      phoneDescription: 'Allow academy phone calls',
      yourRights: 'Your Rights',
      exportData: 'Export My Data',
      exportDescription: 'Download a copy of all your data',
      privacyPolicy: 'Privacy Policy',
      privacyPolicyDescription: 'Read our complete privacy policy',
      deleteData: 'Delete My Data',
      deleteDescription: 'Request permanent deletion of all data',
      importantInfo: 'Important Information',
      infoChangeConsents: '• You can change your consents at any time',
      infoRequiredConsents: '• Some consents are required for basic app functionality',
      infoProcessingTime: '• Export and deletion requests are processed within 30 days',
      infoContact: '• For privacy questions, contact us',
      saveSettings: 'Save Settings',
      settingsSavedSuccess: 'Privacy settings saved successfully',
      settingsSaveError: 'Could not save settings',
      exportDataTitle: 'Export Data',
      exportDataMessage: 'You will receive a file with all your personal data within 30 days, as provided by GDPR.',
      requestSent: 'Request Sent',
      exportRequestMessage: 'Your request has been registered. You will receive the data by email within 30 days.',
      deleteDataTitle: 'Delete Data',
      deleteDataWarning: 'WARNING: This action will permanently delete all your personal data. This action cannot be undone.',
      finalConfirmation: 'Final Confirmation',
      deleteConfirmMessage: 'Are you absolutely sure you want to delete all your data? You will lose access to your account.',
      deleteAll: 'Yes, delete everything',
      requestRegistered: 'Request Registered',
      deleteRequestMessage: 'Your deletion request has been registered. Data will be removed within 30 days.',
      privacyPolicyError: 'Could not open privacy policy',
      profileVisibilityTitle: 'Profile Visibility',
      profileVisibilityQuestion: 'Who can see your basic information?',
      onlyAcademy: 'Academy Only',

      // Admin Classes Screen
      searchClasses: 'Search classes...',
      allClasses: 'All',
      activeClasses: 'Active',
      inactiveClasses: 'Inactive',
      fullClasses: 'Full',
      emptyClasses: 'Empty',
      noInstructor: 'No Instructor',
      notAssigned: 'Not assigned',
      errorLoadingClasses: 'Could not load classes',
      confirmDeletion: 'Confirm Deletion',
      confirmDeleteClass: 'Are you sure you want to delete the class {className}?',
      classDeletedSuccess: 'Class deleted successfully',
      errorDeletingClass: 'Could not delete class',
      edit: 'Edit',
      delete: 'Delete',
      professor: 'Instructor',
      scheduleNotDefined: 'Schedule not defined',
      students: 'students',
      active: 'Active',
      inactive: 'Inactive',
      full: 'Full',
      withoutInstructor: 'No Instructor',
      viewDetails: 'View Details',
      studentsTab: 'Students',
      noClassesFound: 'No classes found',
      noMatchingClasses: 'No classes match your search',
      noClassesRegistered: 'No classes registered yet',
      classStatistics: 'Class Statistics',
      total: 'Total',
      totalStudents: 'Total Students',
      modalities: 'Modalities',
      newClass: 'New Class',

      // Admin Modalities Screen
      fightModalities: 'Fighting Modalities',
      paymentPlans: 'Payment Plans',
      announcementBoard: 'Announcement Board',
      add: 'Add',
      publish: 'Publish',
      noDescription: 'No description',
      noModalitiesRegistered: 'No modalities registered',
      noPlansRegistered: 'No plans registered',
      noAnnouncementsPublished: 'No announcements published',
      summary: 'Summary',
      plans: 'Plans',
      activeAnnouncements: 'Active Announcements',
      errorLoadingData: 'Could not load data',
      modalityNameRequired: 'Modality name is required',
      modalityCreatedSuccess: 'Modality created successfully',
      errorCreatingModality: 'Could not create modality',
      confirmDeleteModality: 'Are you sure you want to delete the modality {modalityName}?\n\nThis action cannot be undone.',
      modalityDeletedSuccess: 'Modality deleted successfully!',
      errorDeletingModality: 'Could not delete modality.\n\nReason: {error}',
      planNameAndValueRequired: 'Plan name and value are required',
      planCreatedSuccess: 'Plan created successfully',
      errorCreatingPlan: 'Could not create plan',
      confirmDeletePlan: 'Are you sure you want to delete the plan {planName}?\n\nThis action cannot be undone.',
      planDeletedSuccess: 'Plan deleted successfully!',
      errorDeletingPlan: 'Could not delete plan.\n\nReason: {error}',
      announcementTitleAndContentRequired: 'Announcement title and content are required',
      announcementPublishedSuccess: 'Announcement published successfully',
      errorPublishingAnnouncement: 'Could not publish announcement',
      confirmDeleteAnnouncement: 'Are you sure you want to delete the announcement "{announcementTitle}"?\n\nThis action cannot be undone.',
      announcementDeletedSuccess: 'Announcement deleted successfully!',
      errorDeletingAnnouncement: 'Could not delete announcement.\n\nReason: {error}',
      noExpirationDate: 'No expiration date',
      expiresOn: 'Expires on:',
      newModality: 'New Modality',
      modalityName: 'Modality Name',
      optionalDescription: 'Description (optional)',
      create: 'Create',
      newPlan: 'New Plan',
      planName: 'Plan Name',
      valueInReais: 'Value ($)',
      durationMonths: 'Duration (months)',
      months: 'month(s)',
      newAnnouncement: 'New Announcement',
      announcementTitle: 'Announcement Title',
      content: 'Content',
      optionalExpirationDate: 'Expiration Date (optional)',
      targetAudience: 'Target Audience:',
      all: 'All',
      students: 'Students',
      instructors: 'Instructors',

      // Instructor Dashboard Screen
      hello: 'Hello',
      martialArtsInstructor: 'Martial Arts Instructor',
      online: 'Online',
      myClasses: 'My Classes',
      totalStudents: 'Total Students',
      classesToday: 'Classes Today',
      checkIns: 'Check-ins',
      todaySchedule: 'Today\'s Schedule',
      classesScheduled: 'class(es) scheduled',
      noClassesToday: 'No classes today',
      planNextClasses: 'Take the opportunity to plan your next classes',
      quickActions: 'Quick Actions',
      directAccessFunctionalities: 'Direct access to main functionalities',
      newClass: 'New Class',
      createNewClass: 'Create new class',
      create: 'Create',
      checkIn: 'Check-in',
      digitalAttendance: 'Digital attendance',
      open: 'Open',
      reports: 'Reports',
      dataAnalysis: 'Data analysis',
      view: 'View',
      announcements: 'Announcements',
      importantCommunications: 'Important communications',
      update: 'Update',
      loadingAnnouncements: 'Loading announcements...',
      important: 'Important',
      noAnnouncementsNow: 'No announcements at the moment',
      notifyNewCommunications: 'You will be notified when there are new communications',
      recentGraduations: 'Recent Graduations',
      noRecentGraduations: 'No recent graduations',
      viewAllGraduations: 'View All Graduations',
      upcomingClasses: 'Upcoming Classes',
      noUpcomingClasses: 'No upcoming classes',
      viewAllClasses: 'View All Classes',
      scheduleNotDefined: 'Schedule not defined',
      students: 'students',
      manageClass: 'Manage Class',
      errorLoadingAnnouncements: 'Error loading announcements:',
      errorLoadingData: 'Error loading data',
      couldNotLoadAnnouncements: 'Could not load announcements. Please try again later.',
      now: 'Now',
      unknownDate: 'Unknown date',
      today: 'Today',
      yesterday: 'Yesterday',
      daysAgo: '{days} days ago',
      errorFormattingDate: 'Error formatting date:',
      loadingInstructorDashboard: '📊 Loading instructor dashboard:',
      classesLoaded: '✅ {count} classes loaded',
      errorSearchingClasses: '⚠️ Error searching classes via service:',
      fallbackClasses: '✅ Fallback: {count} classes found',
      fallbackClassesError: '❌ Fallback failure for classes:',
      studentsLoaded: '✅ {count} students loaded',
      errorSearchingStudents: '⚠️ Error searching students via service:',
      instructorDashboardLoaded: '✅ Instructor dashboard loaded successfully',
      generalErrorLoadingDashboard: 'General error loading instructor dashboard:',

      // InstructorStudents Screen
      searchStudents: 'Search students...',
      allStudents: 'All',
      activeStudents: 'Active',
      inactiveStudents: 'Inactive',
      paymentPendingStudents: 'Payment Pending',
      allGenders: 'All genders',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      minAge: 'Minimum age',
      maxAge: 'Maximum age',
      enrollmentStart: 'Enrollment start',
      enrollmentEnd: 'Enrollment end',
      clearFilters: 'Clear Filters',
      applyFilters: 'Apply Filters',
      viewProfile: 'View Profile',
      graduation: 'Graduation',
      paymentUpToDate: 'Up to date',
      paymentPending: 'Pending',
      paymentOverdue: 'Overdue',
      paymentNA: 'N/A',
      noStudentsFound: 'No students found',
      noStudentsMessage: 'You don\'t have any registered students yet.',
      modality: 'Modality',
      allModalities: 'All modalities',
      loadingStudentsInstructor: '👥 Loading instructor data:',
      searchingStudentsCreatedBy: '🔍 Trying to search students created by this instructor...',
      studentsFoundCreatedBy: '✅ {count} students found via createdBy',
      errorSearchingStudentsService: '⚠️ Error searching students via service:',
      fallbackStudentsFound: '✅ Fallback: {count} students found',
      errorFallback: '❌ Fallback error:',
      classesFound: '✅ {count} classes found',
      errorSearchingClasses: '⚠️ Error searching classes:',
      modalitiesLoaded: '✅ {count} modalities loaded',
      errorSearchingModalities: '⚠️ Error searching modalities:',
      instructorDataLoaded: '✅ Instructor data loaded successfully',
      generalErrorLoadingInstructorData: 'General error loading instructor data:',
      limitedInfoWarning: 'Some information may be limited. Please try again later.',

      // Language Detection
      language: 'en',
    }
  },
  es: {
    code: 'es',
    name: 'Español',
    flag: '🇪🇸',
    strings: {
      // Login Screen
      appName: 'Academia App',
      welcome: '¡Bienvenido de vuelta!',
      email: 'Correo electrónico',
      password: 'Contraseña',
      login: 'Iniciar sesión',
      forgotPassword: 'Olvidé mi contraseña',
      register: 'Crear cuenta',
      language: 'Idioma',
      darkMode: 'Modo oscuro',
      error: 'Error',
      fillAllFields: 'Por favor, completa todos los campos',
      loginError: 'Error de inicio de sesión',
      checkCredentials: 'Verifica tus credenciales',
      userNotFound: 'Usuario no encontrado',
      wrongPassword: 'Contraseña incorrecta',
      invalidCredentials: 'Email o contraseña inválidos. Verifique sus datos e intente de nuevo.',
      invalidEmail: 'Correo electrónico inválido',
      loggingIn: 'Iniciando sesión...',
      
      // Social Login
      orLoginWith: 'O inicia sesión con:',
      
      // Registration Screen
      createAccount: 'Crear Cuenta',
      fillDataToRegister: 'Completa los datos para registrarte',
      personalData: 'Datos Personales',
      fullName: 'Nombre Completo *',
      phoneWhatsApp: 'Teléfono/WhatsApp',
      userType: 'Tipo de Usuario',
      passwordSection: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña *',
      creatingAccount: 'Creando cuenta...',
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
      signIn: 'Iniciar Sesión',
      
      // User Types
      student: 'Estudiante',
      instructor: 'Instructor',
      administrator: 'Administrador',
      studentDescription: 'Acceso a clases y progreso',
      instructorDescription: 'Gestionar clases y estudiantes',
      adminDescription: 'Control total del sistema',
      
      // Validation Messages
      nameRequired: 'El nombre es obligatorio',
      emailRequired: 'El correo electrónico es obligatorio',
      passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
      passwordsMismatch: 'Las contraseñas no coinciden',
      
      // Success and Error Messages
      accountCreatedSuccess: '¡Cuenta creada exitosamente! 🎉',
      registrationError: 'Error al crear la cuenta',
      emailAlreadyInUse: 'Este correo electrónico ya está en uso',
      weakPassword: 'Contraseña muy débil',
      googleLoginError: 'Error al iniciar sesión con Google',
      facebookLoginError: 'Error al iniciar sesión con Facebook',
      microsoftLoginError: 'Error al iniciar sesión con Microsoft',
      appleLoginError: 'Error al iniciar sesión con Apple',
      
      // Common
      required: 'obligatorio',
      success: 'Éxito',
      loading: 'Cargando...',
      save: 'Guardar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      delete: 'Eliminar',
      edit: 'Editar',
      back: 'Atrás',
      next: 'Siguiente',
      finish: 'Finalizar',
      yes: 'Sí',
      no: 'No',
      ok: 'OK',
      
      // Fallback messages
      recoverPassword: 'Recuperar Contraseña',
      contactSupport: 'Por favor contacta a soporte para recuperar tu contraseña.',
      registrationDevelopment: 'Funcionalidad de registro en desarrollo',
      
      // Navigation and Menu
      dashboard: 'Dashboard',
      payments: 'Pagos',
      evolution: 'Evolución',
      calendar: 'Calendario',
      reports: 'Reportes',
      classes: 'Clases',
      students: 'Estudiantes',
      management: 'Gestión',
      invitations: 'Invitaciones',
      settings: 'Configuraciones',
      profile: 'Perfil',
      notifications: 'Notificaciones',
      academy: 'Academia',
      
      // Form Labels and Placeholders
      selectOption: 'Selecciona una opción',
      typeNumber: 'Digite el número',
      academyCodeOrLink: 'Código de la academia o enlace completo',
      searchStudents: 'Buscar estudiantes...',
      searchClasses: 'Buscar clases...',
      academyCode: 'Código de la Academia',
      postalCode: 'Código Postal',
      number: 'Número',
      address: 'Dirección',
      emergencyContact: 'Contacto de Emergencia',
      medicalInformation: 'Información Médica',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condiciones médicas...',
      birthDate: 'Fecha de Nacimiento',
      birthDatePlaceholder: '01/01/1990',
      goals: 'Objetivos',
      goalsPlaceholder: 'Pérdida de peso, ganancia muscular, acondicionamiento...',
      medicalConditions: 'Condiciones Médicas (opcional)',
      medicalConditionsPlaceholder: 'Informa alergias, lesiones, medicamentos, etc.',
      emergencyPhone: 'Teléfono de Emergencia',
      addressOptional: 'Dirección (opcional)',
      
      // Physical Evaluation
      physicalEvaluations: 'Evaluaciones físicas',
      physicalEvaluation: 'Evaluación Física',
      myInjuries: 'Mis Lesiones',
      currentGraduation: 'Graduación Actual',
      startDate: 'Fecha de Inicio',
      evaluationNotes: 'Notas de evaluación',
      evaluationNotesPlaceholder: 'Ej.: Inicio de nueva dieta, cambio de entrenamiento, etc.',
      
      // Injury Management
      injuryDescription: 'Descripción de la Lesión',
      injuryDescriptionPlaceholder: 'Describe cómo ocurrió la lesión, síntomas, etc.',
      treatment: 'Tratamiento',
      treatmentPlaceholder: 'Ej.: Fisioterapia, medicamentos, reposo...',
      medicalNotes: 'Notas Médicas',
      medicalNotesPlaceholder: 'Instrucciones del médico, diagnóstico...',
      recoveryTime: 'Tiempo de Recuperación',
      recoveryTimePlaceholder: 'Ej.: 2 semanas, 1 mes...',
      restrictions: 'Restricciones',
      restrictionsPlaceholder: 'Ej.: No hacer fuerza con el brazo, evitar correr...',
      
      // Class Management
      description: 'Descripción',
      descriptionOptional: 'Descripción (opcional)',
      maxStudents: 'Máximo de Estudiantes',
      schedule: 'Horario',
      scheduleExample: 'Ej.: Lunes 19:00',
      scheduleDetailed: 'Horario (ej.: Lunes 08:00-09:00)',
      monthlyPrice: 'Precio Mensual ($)',
      maxCapacity: 'Capacidad Máxima',
      className: 'Nombre de la Clase',
      
      // Student Management
      phoneNotInformed: 'Teléfono no informado',
      disassociationReason: 'Motivo de desasociación *',
      disassociationReasonPlaceholder: 'Proporciona el motivo de desasociación (ej.: impago, solicitud del estudiante, etc.)',
      minAge: 'Edad mín.',
      maxAge: 'Edad máx.',
      until: 'Hasta (AAAA-MM-DD)',
      
      // Payment and Dates
      dueDatePlaceholder: 'DD/MM/AAAA',
      
      // User Information
      user: 'Usuario',
      personalInformation: 'Información personal y configuraciones',
      updatePassword: 'Actualiza tu contraseña de acceso',
      changePassword: 'Cambiar Contraseña',
      bodyMeasurements: 'Registra tus medidas corporales',
      physicalEvolution: 'Sigue tu evolución física',
      
      // Evolution and Goals
      maintainFrequency: 'Mantener frecuencia en clases',
      improveTechniques: 'Perfeccionar técnicas',
      nextGraduation: 'Próxima graduación',
      
      // Statistics
      thisMonth: 'Este mes',
      plusThisMonth: '+15 este mes',
      averageFrequency: 'Frecuencia Promedio',
      plusVsLastMonth: '+3% vs mes anterior',
      
      // Admin Actions
      quickActions: 'Acciones Rápidas',
      modalitiesConfig: 'Configurar modalidades',
      preferencesManagement: 'Preferencias y gestión',
      addGraduation: 'Agregar Graduación',
      
      // Error Messages
      cannotLoadPayments: 'No se pudieron cargar los pagos',
      whatsappNotFound: 'Número de WhatsApp de la academia no encontrado',
      cannotOpenWhatsapp: 'No se pudo abrir WhatsApp',
      logoutNotAvailable: 'Función de logout no disponible. Recarga la app.',
      cannotLogout: 'No se pudo cerrar sesión. Intenta nuevamente.',
      cannotLoadClasses: 'No se pudieron cargar las clases',
      cannotUpdateProfile: 'No se pudo actualizar el perfil',
      cannotDeleteClass: 'No se pudo eliminar la clase. Verifica tus permisos.',
      cannotLoadStudents: 'No se pudieron cargar los estudiantes',
      cannotDeleteStudent: 'No se pudo eliminar el estudiante',
      invalidCode: 'Ingresa un código válido',
      cannotProcessCode: 'No se pudo procesar el código',
      invalidQRCode: 'Código QR inválido',
      invalidOrExpiredInvite: 'Invitación inválida o expirada',
      invalidLink: 'Enlace inválido',
      pleaseValidEmail: 'Por favor, ingresa un email válido',
      userDataNotFound: 'Datos de usuario o clase no encontrados',
      cannotCopyLink: 'No se pudo copiar el enlace',
      checkInTimeError: 'Check-in solo se puede hacer 15 minutos antes o después de la hora de clase',
      
      // Success Messages
      classDeletedSuccess: 'Clase eliminada exitosamente',
      studentDeletedSuccess: 'Estudiante eliminado exitosamente',
      
      // Development Messages
      inDevelopment: 'En Desarrollo',
      exportFeatureComingSoon: 'Funcionalidad de exportación se implementará pronto',
      featureComingSoon: 'Funcionalidad se implementará pronto',
      limitedInformation: 'Alguna información puede estar limitada. Intenta nuevamente más tarde.',
      adminOnlyFeature: 'Funcionalidad disponible solo para administradores',
      
      // Alert Titles
      checkIn: 'Check-in',
      warning: 'Advertencia',
      info: 'Info',
      mandatorySelection: 'Selección Obligatoria',
      pleaseSelectUserType: 'Por favor, selecciona el tipo de usuario.',
      cannotSaveUserType: 'No se pudo guardar el tipo de usuario. Intenta nuevamente.',
      
      // Notification Service
      congratsNewGraduation: '¡Felicitaciones! Nueva Graduación',
      newAnnouncement: 'Nuevo Anuncio',
      
      // Logout Confirmation
      confirmExit: 'Confirmar Salida',
      sureToLogout: '¿Estás seguro de que quieres cerrar sesión?',
      exit: 'Salir',
      
      // Payment Status
      paid: 'Pagado',
      pending: 'Pendiente',
      overdue: 'Vencido',
      notInformed: 'No informado',
      pixPayment: 'Pago PIX',
      pixFeatureComingSoon: 'La funcionalidad de pago PIX se implementará pronto',
      
      // Navigation Titles
      newClass: 'Nueva Clase',
      classStudents: 'Estudiantes de la Clase',
      editClass: 'Editar Clase',
      classDetails: 'Detalles de la Clase',
      checkIns: 'Check-ins',
      newStudent: 'Nuevo Estudiante',
      editStudent: 'Editar Estudiante',
      studentDetails: 'Detalles del Estudiante',
      studentPayments: 'Pagos del Estudiante',
      reports: 'Reportes',
      newLesson: 'Nueva Lección',
      myProfile: 'Mi Perfil',
      changePassword: 'Cambiar Contraseña',
      physicalEvaluation: 'Evaluación Física',
      evaluationHistory: 'Historial de Evaluaciones',
      manageInjury: 'Gestionar Lesión',
      myInjuries: 'Mis Lesiones',
      privacyPolicy: 'Política de Privacidad',
      notificationSettings: 'Configuración de Notificaciones',
      privacySettings: 'Configuración de Privacidad',
      
      // Navigation Subtitles
      personalInfoAndSettings: 'Información personal y configuración',
      updateYourPassword: 'Actualiza tu contraseña de acceso',
      recordBodyMeasurements: 'Registra tus medidas corporales',
      trackPhysicalEvolution: 'Sigue tu evolución física',
      recordAndTrackInjuries: 'Registra y sigue las lesiones',
      injuryHistoryAndRecovery: 'Historial de lesiones y recuperación',
      dataProtectionAndLGPD: 'Protección de datos y LGPD',
      manageYourNotifications: 'Gestiona tus notificaciones',
      lgpdAndDataProtection: 'LGPD y protección de datos',
      
      // Tab Navigation
      dashboard: 'Panel',
      payments: 'Pagos',
      evolution: 'Evolución',
      calendar: 'Calendario',
      students: 'Estudiantes',
      classes: 'Clases',
      modalities: 'Modalidades',
      checkIn: 'Check-in',
      instructorReports: 'Reportes',
      lessons: 'Lecciones',
      studentDashboard: 'Panel del Estudiante',
      invites: 'Invitaciones',
      
      // Profile Screen
      loadingStudentData: 'Error al cargar datos del estudiante',
      loadingPaymentData: 'Error al cargar pago actual',
      checkingPaymentDue: 'Error al verificar vencimiento',
      monthlyPayment: 'Pago Mensual',
      profileUpdatedSuccess: 'Perfil actualizado exitosamente',
      cannotUpdateProfile: 'No se pudo actualizar el perfil',
      confirmLogout: '¿Estás seguro de que quieres cerrar sesión?',
      logout: 'Cerrar Sesión',
      user: 'Usuario',
      paymentNearDue: 'Pago Próximo al Vencimiento',
      paymentDueToday: 'hoy',
      paymentDueTomorrow: 'mañana',
      paymentDueInDays: 'días',
      paymentDueText: 'Tu pago de {planName} vence en {days}',
      dateLabel: 'Fecha',
      valueLabel: 'Monto',
      changeDate: 'Cambiar Fecha',
      payNow: 'Pagar Ahora',
      personalInformation: 'Información Personal',
      cancel: 'Cancelar',
      edit: 'Editar',
      fullName: 'Nombre Completo',
      phoneWhatsApp: 'Teléfono/WhatsApp',
      address: 'Dirección',
      emergencyContact: 'Contacto de Emergencia',
      medicalInformation: 'Información Médica',
      allergiesMedicationsConditions: 'Alergias, medicamentos, condiciones médicas...',
      saveChanges: 'Guardar Cambios',
      name: 'Nombre',
      phone: 'Teléfono',
      notInformed: 'No informado',
      academyInformation: 'Información de la Academia',
      currentGraduation: 'Graduación Actual',
      beginner: 'Principiante',
      currentPlan: 'Plan Actual',
      notDefined: 'No definido',
      startDate: 'Fecha de Inicio',
      contracts: 'Contratos',
      nextDueDate: 'Próximo vencimiento',
      checkIns: 'Check-ins',
      checkInsThisWeek: 'Check-ins esta semana',
      physicalEvaluations: 'Evaluaciones físicas',
      evaluationsRegistered: 'evaluación(es) registrada(s)',
      noEvaluationsRegistered: 'Ninguna evaluación registrada',
      myInjuries: 'Mis Lesiones',
      injuriesRegistered: 'lesión(es) registrada(s)',
      noInjuriesRegistered: 'Ninguna lesión registrada',
      noTrainingThisWeek: 'Ningún entrenamiento esta semana',
      
      // Forgot Password Screen
      emailRequired: 'Email es obligatorio',
      invalidEmail: 'Email inválido',
      pleaseValidEmail: 'Por favor, ingresa un email válido',
      emailSentSuccess: '¡Email enviado! ⚠️ IMPORTANTE: Revisa tu carpeta de SPAM/CORREO NO DESEADO, ya que los emails de recuperación suelen ser filtrados.',
      resetPasswordError: 'Error al enviar email de recuperación',
      emailNotFound: 'Email no encontrado. Verifica si es correcto o crea una cuenta.',
      invalidEmailFormat: 'Email inválido. Verifica el formato.',
      tooManyRequests: 'Demasiados intentos. Espera unos minutos e intenta de nuevo.',
      networkError: 'Error de conexión. Verifica tu internet e intenta de nuevo.',
      configurationNotFound: 'Configuración de email no encontrada. Contacta soporte.',
      close: 'Cerrar',
      recoverPassword: 'Recuperar Contraseña',
      enterEmailForInstructions: 'Ingresa tu email para recibir instrucciones',
      sendEmail: 'Enviar Email',
      emailSent: '¡Email Enviado!',
      checkInboxInstructions: 'Revisa tu bandeja de entrada y sigue las instrucciones para restablecer tu contraseña.',
      spamFolderWarning: '⚠️ IMPORTANTE: Si no encuentras el email, revisa tu carpeta de SPAM/CORREO NO DESEADO, ya que los emails de recuperación suelen ser filtrados.',
      backToLogin: 'Volver al Login',
      
      // Academia Selection Screen
      enterAcademyCode: 'Ingresa el código de la academia',
      academyFoundSuccess: '¡Academia encontrada exitosamente!',
      academyNotFound: 'Academia no encontrada. Verifica el código e intenta de nuevo',
      errorSearchingAcademy: 'Error al buscar academia. Intenta de nuevo',
      associatedSuccessfully: '¡Has sido asociado exitosamente con la academia!',
      errorAssociating: 'Error al asociar con la academia. Intenta de nuevo',
      invalidQRCode: 'Código QR inválido',
      errorProcessingQR: 'Error al procesar código QR',
      invalidOrExpiredInvite: 'Invitación inválida o expirada',
      errorProcessingInvite: 'Error al procesar invitación',
      enterInviteLink: 'Ingresa el enlace de invitación',
      invalidLink: 'Enlace inválido',
      errorProcessingInviteLink: 'Error al procesar enlace de invitación',
      permissionDenied: 'Permiso Denegado',
      onlyAdminsCanCreate: 'Solo usuarios con perfil de administrador pueden crear una nueva academia.',
      currentProfile: 'Tu perfil actual',
      notDefined: 'no definido',
      academyNameRequired: 'Nombre de la academia es obligatorio',
      emailRequired: 'Email es obligatorio',
      cityRequired: 'Ciudad es obligatoria',
      streetRequired: 'Calle/Avenida es obligatoria',
      phoneRequired: 'Teléfono es obligatorio',
      invalidEmail: 'Email inválido',
      academyCreatedSuccess: '¡Academia Creada Exitosamente! 🎉',
      academyCreatedMessage: '¡Tu academia ha sido creada!\n\n📋 CÓDIGO DE LA ACADEMIA: {code}\n\n⚠️ IMPORTANTE: ¡Anota este código! Los usuarios lo necesitarán para asociarse con tu academia.\n\nSerás redirigido al dashboard en unos segundos.',
      copyCode: 'Copiar Código',
      ok: 'OK',
      cannotCreateAcademy: 'No se pudo crear la academia. Intenta de nuevo',
      addressNotInformed: 'Dirección no informada',
      logoutError: 'Error al cerrar sesión',
      errorLoggingOut: 'Error al salir. Intenta de nuevo.',
      createAcademy: 'Crear Academia',
      selectAcademy: 'Seleccionar Academia',
      adminMustCreate: 'Como administrador, necesitas crear una nueva academia',
      mustAssociate: 'Para continuar, necesitas asociarte con una academia',
      academyCode: 'Código de la Academia',
      academyCodePlaceholder: 'Ej: ABC123',

      // Privacy Settings Screen
      privacySettings: 'Configuraciones de Privacidad',
      lgpdStatus: 'Estado GDPR',
      consents: 'Consentimientos',
      lgpdInfo: 'La Ley General de Protección de Datos (GDPR) garantiza tus derechos sobre tus datos personales. Configura a continuación cómo se pueden usar tus datos.',
      consentGivenOn: 'Consentimiento inicial dado el:',
      dataProcessingConsent: 'Procesamiento de Datos Personales',
      dataProcessingDescription: 'Permitir el uso de datos para funcionalidad básica de la app',
      marketingConsent: 'Comunicaciones de Marketing',
      marketingDescription: 'Recibir ofertas, promociones y noticias',
      analyticsConsent: 'Análisis y Mejoras',
      analyticsDescription: 'Usar datos para mejorar la app y servicios',
      thirdPartyConsent: 'Compartir con Terceros',
      thirdPartyDescription: 'Permitir compartir con socios (opcional)',
      profileVisibility: 'Visibilidad del Perfil',
      profileVisibilityDescription: 'Actualmente:',
      public: 'Público',
      academy: 'Solo Academia',
      private: 'Privado',
      shareTrainingData: 'Compartir Datos de Entrenamiento',
      shareTrainingDescription: 'Permitir que instructores vean tu progreso',
      shareProgressData: 'Compartir Datos de Progreso',
      shareProgressDescription: 'Permitir comparaciones y estadísticas generales',
      contactMethods: 'Métodos de Contacto',
      whatsappContact: 'Contacto por WhatsApp',
      whatsappDescription: 'Permitir contacto de la academia por WhatsApp',
      emailContact: 'Contacto por Email',
      emailDescription: 'Permitir contacto de la academia por email',
      phoneContact: 'Contacto Telefónico',
      phoneDescription: 'Permitir llamadas de la academia',
      yourRights: 'Tus Derechos',
      exportData: 'Exportar Mis Datos',
      exportDescription: 'Descargar una copia de todos tus datos',
      privacyPolicy: 'Política de Privacidad',
      privacyPolicyDescription: 'Leer nuestra política de privacidad completa',
      deleteData: 'Eliminar Mis Datos',
      deleteDescription: 'Solicitar eliminación permanente de todos los datos',
      importantInfo: 'Información Importante',
      infoChangeConsents: '• Puedes cambiar tus consentimientos en cualquier momento',
      infoRequiredConsents: '• Algunos consentimientos son necesarios para la funcionalidad básica de la app',
      infoProcessingTime: '• Las solicitudes de exportación y eliminación se procesan en 30 días',
      infoContact: '• Para preguntas sobre privacidad, contáctanos',
      saveSettings: 'Guardar Configuraciones',
      settingsSavedSuccess: 'Configuraciones de privacidad guardadas exitosamente',
      settingsSaveError: 'No se pudieron guardar las configuraciones',
      exportDataTitle: 'Exportar Datos',
      exportDataMessage: 'Recibirás un archivo con todos tus datos personales en 30 días, según lo previsto por GDPR.',
      requestSent: 'Solicitud Enviada',
      exportRequestMessage: 'Tu solicitud ha sido registrada. Recibirás los datos por email en 30 días.',
      deleteDataTitle: 'Eliminar Datos',
      deleteDataWarning: 'ADVERTENCIA: Esta acción eliminará permanentemente todos tus datos personales. Esta acción no se puede deshacer.',
      finalConfirmation: 'Confirmación Final',
      deleteConfirmMessage: '¿Estás absolutamente seguro de que quieres eliminar todos tus datos? Perderás acceso a tu cuenta.',
      deleteAll: 'Sí, eliminar todo',
      requestRegistered: 'Solicitud Registrada',
      deleteRequestMessage: 'Tu solicitud de eliminación ha sido registrada. Los datos serán eliminados en 30 días.',
      privacyPolicyError: 'No se pudo abrir la política de privacidad',
      profileVisibilityTitle: 'Visibilidad del Perfil',
      profileVisibilityQuestion: '¿Quién puede ver tu información básica?',
      onlyAcademy: 'Solo Academia',

      // Admin Classes Screen
      searchClasses: 'Buscar clases...',
      allClasses: 'Todas',
      activeClasses: 'Activas',
      inactiveClasses: 'Inactivas',
      fullClasses: 'Llenas',
      emptyClasses: 'Vacías',
      noInstructor: 'Sin Instructor',
      notAssigned: 'No asignado',
      errorLoadingClasses: 'No se pudieron cargar las clases',
      confirmDeletion: 'Confirmar Eliminación',
      confirmDeleteClass: '¿Estás seguro de que quieres eliminar la clase {className}?',
      classDeletedSuccess: 'Clase eliminada exitosamente',
      errorDeletingClass: 'No se pudo eliminar la clase',
      edit: 'Editar',
      delete: 'Eliminar',
      professor: 'Instructor',
      scheduleNotDefined: 'Horario no definido',
      students: 'estudiantes',
      active: 'Activa',
      inactive: 'Inactiva',
      full: 'Llena',
      withoutInstructor: 'Sin Instructor',
      viewDetails: 'Ver Detalles',
      studentsTab: 'Estudiantes',
      noClassesFound: 'No se encontraron clases',
      noMatchingClasses: 'Ninguna clase coincide con tu búsqueda',
      noClassesRegistered: 'No hay clases registradas aún',
      classStatistics: 'Estadísticas de Clases',
      total: 'Total',
      totalStudents: 'Total Estudiantes',
      modalities: 'Modalidades',
      newClass: 'Nueva Clase',

      // Admin Modalities Screen
      fightModalities: 'Modalidades de Lucha',
      paymentPlans: 'Planes de Pago',
      announcementBoard: 'Tablón de Anuncios',
      add: 'Agregar',
      publish: 'Publicar',
      noDescription: 'Sin descripción',
      noModalitiesRegistered: 'No hay modalidades registradas',
      noPlansRegistered: 'No hay planes registrados',
      noAnnouncementsPublished: 'No hay anuncios publicados',
      summary: 'Resumen',
      plans: 'Planes',
      activeAnnouncements: 'Anuncios Activos',
      errorLoadingData: 'No se pudieron cargar los datos',
      modalityNameRequired: 'El nombre de la modalidad es obligatorio',
      modalityCreatedSuccess: 'Modalidad creada exitosamente',
      errorCreatingModality: 'No se pudo crear la modalidad',
      confirmDeleteModality: '¿Estás seguro de que quieres eliminar la modalidad {modalityName}?\n\nEsta acción no se puede deshacer.',
      modalityDeletedSuccess: '¡Modalidad eliminada exitosamente!',
      errorDeletingModality: 'No se pudo eliminar la modalidad.\n\nMotivo: {error}',
      planNameAndValueRequired: 'El nombre y valor del plan son obligatorios',
      planCreatedSuccess: 'Plan creado exitosamente',
      errorCreatingPlan: 'No se pudo crear el plan',
      confirmDeletePlan: '¿Estás seguro de que quieres eliminar el plan {planName}?\n\nEsta acción no se puede deshacer.',
      planDeletedSuccess: '¡Plan eliminado exitosamente!',
      errorDeletingPlan: 'No se pudo eliminar el plan.\n\nMotivo: {error}',
      announcementTitleAndContentRequired: 'El título y contenido del anuncio son obligatorios',
      announcementPublishedSuccess: 'Anuncio publicado exitosamente',
      errorPublishingAnnouncement: 'No se pudo publicar el anuncio',
      confirmDeleteAnnouncement: '¿Estás seguro de que quieres eliminar el anuncio "{announcementTitle}"?\n\nEsta acción no se puede deshacer.',
      announcementDeletedSuccess: '¡Anuncio eliminado exitosamente!',
      errorDeletingAnnouncement: 'No se pudo eliminar el anuncio.\n\nMotivo: {error}',
      noExpirationDate: 'Sin fecha de expiración',
      expiresOn: 'Expira el:',
      newModality: 'Nueva Modalidad',
      modalityName: 'Nombre de la Modalidad',
      optionalDescription: 'Descripción (opcional)',
      create: 'Crear',
      newPlan: 'Nuevo Plan',
      planName: 'Nombre del Plan',
      valueInReais: 'Valor ($)',
      durationMonths: 'Duración (meses)',
      months: 'mes(es)',
      newAnnouncement: 'Nuevo Anuncio',
      announcementTitle: 'Título del Anuncio',
      content: 'Contenido',
      optionalExpirationDate: 'Fecha de Expiración (opcional)',
      targetAudience: 'Público objetivo:',
      all: 'Todos',
      students: 'Estudiantes',
      instructors: 'Instructores',

      // Instructor Dashboard Screen
      hello: 'Hola',
      martialArtsInstructor: 'Instructor de Artes Marciales',
      online: 'En línea',
      myClasses: 'Mis Clases',
      totalStudents: 'Total Estudiantes',
      classesToday: 'Clases Hoy',
      checkIns: 'Check-ins',
      todaySchedule: 'Horario de Hoy',
      classesScheduled: 'clase(s) programada(s)',
      noClassesToday: 'No hay clases hoy',
      planNextClasses: 'Aprovecha para planificar tus próximas clases',
      quickActions: 'Acciones Rápidas',
      directAccessFunctionalities: 'Acceso directo a las principales funcionalidades',
      newClass: 'Nueva Clase',
      createNewClass: 'Crear nueva clase',
      create: 'Crear',
      checkIn: 'Check-in',
      digitalAttendance: 'Asistencia digital',
      open: 'Abrir',
      reports: 'Reportes',
      dataAnalysis: 'Análisis de datos',
      view: 'Ver',
      announcements: 'Anuncios',
      importantCommunications: 'Comunicaciones importantes',
      update: 'Actualizar',
      loadingAnnouncements: 'Cargando anuncios...',
      important: 'Importante',
      noAnnouncementsNow: 'No hay anuncios en este momento',
      notifyNewCommunications: 'Serás notificado cuando haya nuevas comunicaciones',
      recentGraduations: 'Graduaciones Recientes',
      noRecentGraduations: 'No hay graduaciones recientes',
      viewAllGraduations: 'Ver Todas las Graduaciones',
      upcomingClasses: 'Próximas Clases',
      noUpcomingClasses: 'No hay clases próximas',
      viewAllClasses: 'Ver Todas las Clases',
      scheduleNotDefined: 'Horario no definido',
      students: 'estudiantes',
      manageClass: 'Gestionar Clase',
      errorLoadingAnnouncements: 'Error al cargar anuncios:',
      errorLoadingData: 'Error al cargar datos',
      couldNotLoadAnnouncements: 'No se pudieron cargar los anuncios. Inténtalo de nuevo más tarde.',
      now: 'Ahora',
      unknownDate: 'Fecha desconocida',
      today: 'Hoy',
      yesterday: 'Ayer',
      daysAgo: 'Hace {days} días',
      errorFormattingDate: 'Error al formatear fecha:',
      loadingInstructorDashboard: '📊 Cargando panel del instructor:',
      classesLoaded: '✅ {count} clases cargadas',
      errorSearchingClasses: '⚠️ Error al buscar clases via servicio:',
      fallbackClasses: '✅ Respaldo: {count} clases encontradas',
      fallbackClassesError: '❌ Falla en respaldo para clases:',
      studentsLoaded: '✅ {count} estudiantes cargados',
      errorSearchingStudents: '⚠️ Error al buscar estudiantes via servicio:',
      instructorDashboardLoaded: '✅ Panel del instructor cargado exitosamente',
      generalErrorLoadingDashboard: 'Error general al cargar panel del instructor:',

      // InstructorStudents Screen
      searchStudents: 'Buscar estudiantes...',
      allStudents: 'Todos',
      activeStudents: 'Activos',
      inactiveStudents: 'Inactivos',
      paymentPendingStudents: 'Pago Pendiente',
      allGenders: 'Todos los géneros',
      male: 'Masculino',
      female: 'Femenino',
      other: 'Otro',
      minAge: 'Edad mínima',
      maxAge: 'Edad máxima',
      enrollmentStart: 'Inicio de inscripción',
      enrollmentEnd: 'Fin de inscripción',
      clearFilters: 'Limpiar Filtros',
      applyFilters: 'Aplicar Filtros',
      viewProfile: 'Ver Perfil',
      graduation: 'Graduación',
      paymentUpToDate: 'Al día',
      paymentPending: 'Pendiente',
      paymentOverdue: 'Atrasado',
      paymentNA: 'N/A',
      noStudentsFound: 'No se encontraron estudiantes',
      noStudentsMessage: 'Aún no tienes estudiantes registrados.',
      modality: 'Modalidad',
      allModalities: 'Todas las modalidades',
      loadingStudentsInstructor: '👥 Cargando datos del instructor:',
      searchingStudentsCreatedBy: '🔍 Intentando buscar estudiantes creados por este instructor...',
      studentsFoundCreatedBy: '✅ {count} estudiantes encontrados via createdBy',
      errorSearchingStudentsService: '⚠️ Error al buscar estudiantes via servicio:',
      fallbackStudentsFound: '✅ Fallback: {count} estudiantes encontrados',
      errorFallback: '❌ Error en fallback:',
      classesFound: '✅ {count} clases encontradas',
      errorSearchingClasses: '⚠️ Error al buscar clases:',
      modalitiesLoaded: '✅ {count} modalidades cargadas',
      errorSearchingModalities: '⚠️ Error al buscar modalidades:',
      instructorDataLoaded: '✅ Datos del instructor cargados exitosamente',
      generalErrorLoadingInstructorData: 'Error general al cargar datos del instructor:',
      limitedInfoWarning: 'Alguna información puede estar limitada. Intente nuevamente más tarde.',

      // Language Detection
      language: 'es',
    }
  }
};

